version: '3.8'
services:
  app:
    build: .
    container_name: python_app
    ports:
      - "6666:80"
    environment:
      - MONGO_URI=mongodb://root:1234567@mongodb:27017/PigSpeech?authSource=admin&retryWrites=true&w=majority
    depends_on:
      - mongo

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234567
    ports:
      - 27017:27017
    restart: unless-stopped